name: Build and Test Java Application

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2.2.0
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew build --stacktrace
      - name: Run Tests with Gradle
        run: ./gradlew test

